export enum AuthTypes {
  LOAD_TOKEN = 'auth/LOAD_TOKEN',
  SIGN_IN_FAILURE = 'auth/SIGN_IN_FAILURE',
  SIGN_IN_REQUEST = 'auth/SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'auth/SIGN_IN_SUCCESS',
  SIGN_OUT_REQUEST = 'auth/SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS = 'auth/SIGN_OUT_SUCCESS',
}
