export enum OccurrenceTypes {
  LIST_OCCURRENCES_FAILURE = 'occurrences/LIST_OCCURRENCES_FAILURE',
  LIST_OCCURRENCES_REQUEST = 'occurrences/LIST_OCCURRENCES_REQUEST',
  LIST_OCCURRENCES_SUCCESS = 'occurrences/LIST_OCCURRENCES_SUCCESS',
}
